name: shell commands

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
     - name: string
       run: echo "welcome to newyork"
     - name: multiple script
       run:
         node -v
         npm -v 
     - name: pythjon command
       run: 
         import platform
         print(platform.processor())
       shell: python 